project_id = "pwhvwckxrgjpisilagjd"

[functions.generate-sitemap]
verify_jwt = false

[functions.generate-llms]
verify_jwt = false

[functions.generate-about]
verify_jwt = false

[functions.generate-prerender]
verify_jwt = false
